"""Add discount fields to products

Revision ID: 4f2d76574ea1
Revises: 
Create Date: 2025-11-08 16:58:11.408873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2d76574ea1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('discount_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_end_date')
    op.drop_column('products', 'discount_price')
    # ### end Alembic commands ###
